name: Thom
favicon: null
layout_spectrum: 0.3099849526770413
typography_spectrum: 0.3716382230632007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8413642069790512
  lightness: 0.17201443086378276
  saturation: 0.41588613856583834
  rhythmicContrast: 0.392063831910491
purpose: []
